name: agentic_reasoning
channels:
  - conda-forge
  - defaults
dependencies:
  - appnope
  - asttokens
  - bzip2
  - ca-certificates
  - comm
  - debugpy
  - decorator
  - exceptiongroup
  - executing
  - importlib-metadata
  - ipykernel
  - jedi
  - jupyter_client
  - jupyter_core
  - krb5
  - libcxx
  - libedit
  - libffi
  - libsodium
  - matplotlib-inline
  - ncurses
  - nest-asyncio
  - openssl
  - packaging
  - parso
  - pexpect
  - pickleshare
  - pip
  - platformdirs
  - prompt-toolkit
  - ptyprocess
  - pure_eval
  - pygments
  - python=3.11.10
  - python-dateutil
  - pyzmq
  - readline
  - setuptools
  - six
  - sqlite
  - stack_data
  - tk
  - tornado
  - traitlets
  - typing_extensions
  - wcwidth
  - wheel
  - xz
  - zeromq
  - zipp
  - zlib
  - pip:
    - nano_graphrag==0.0.8.2
    - future>=1.0.0
    - networkx==3.4.2
    - graspologic==3.4.1
    - nano-vectordb==0.0.4.3
    - hnswlib==0.8.0
    - xxhash==3.5.0
    - dspy-ai==2.6.10
    - neo4j==5.28.1
    - dspy==2.6.10
    - POT==0.9.5
    - anytree==2.12.1
    - beartype==0.18.5
    - gensim==4.3.3
    - graspologic-native==1.2.3
    - hyppo==0.4.0
    - joblib==1.4.2
    - matplotlib==3.10.1
    - numpy==1.26.4
    - scikit-learn==1.6.1
    - scipy==1.12.0
    - seaborn==0.13.2
    - statsmodels==0.14.4
    - umap-learn==0.5.7
    - pytz==2025.1
    - pandas==2.2.3
    - ujson==5.10.0
    - datasets==2.21.0
    - optuna==4.2.1
    - jinja2==3.1.5
    - magicattr==0.1.6
    - litellm==1.62.1
    - diskcache==5.6.3
    - json-repair==0.39.1
    - asyncer==0.0.8
    - cloudpickle==3.1.1
    - smart-open==7.1.0
    - numba==0.61.0
    - autograd==1.7.0
    - contourpy==1.3.1
    - cycler==0.12.1
    - fonttools==4.56.0
    - kiwisolver==1.4.8
    - pillow==11.1.0
    - pyparsing==3.2.1
    - threadpoolctl==3.5.0
    - patsy==1.0.1
    - pynndescent==0.5.13
    - MarkupSafe==3.0.2
    - pyarrow==19.0.1
    - SQLAlchemy==2.0.38
    - tzdata==2025.1
    - colorlog==6.9.0
    - multiprocess==0.70.16
    - aiohappyeyeballs==2.4.8
    - aiosignal==1.3.2
    - attrs==25.1.0
    - frozenlist==1.5.0
    - greenlet==3.1.1
    - jsonschema-specifications==2024.10.1
    - multidict==6.1.0
    - propcache==0.3.0
    - referencing==0.36.2
    - rpds-py==0.23.1
    - yarl==1.18.3
    - Mako==1.3.9
    - alembic==1.14.1
    - fsspec==2024.6.1
    - aiohttp==3.11.13
    - jsonschema==4.23.0
    - llvmlite==0.44.0
    - pydantic-ai==0.0.31
    - pydantic-ai-slim==0.0.31
    - langchain==0.3.19
    - langchain-core==0.3.40
    - langchain-huggingface==0.1.2
    - langchain-qdrant==0.2.0
    - langchain-text-splitters==0.3.6
    - langsmith==0.3.11
    - trafilatura==2.0.0
    - qdrant-client==1.13.2
    - pdfplumber==0.11.5
    - nltk==3.9.1
    - transformers==4.49.0
    - torch==2.2.2
    - requests-toolbelt==1.0.0
    - jsonpatch==1.33
    - zstandard==0.23.0
    - lxml==5.3.1
    - htmldate==1.9.3
    - justext==3.0.2
    - courlan==1.3.2
    - h2==4.2.0
    - hyperframe==6.1.0
    - hpack==4.1.0
    - jsonpointer==3.0.0
    - tld==0.13
    - babel==2.17.0
    - tzlocal==5.3
    - cffi==1.17.1
    - pycparser==2.22
    - pypdfium2==4.30.1
    - sentence-transformers==3.4.1
    - cryptography==44.0.2
